exp:
  run_func:
    _target_: experiments.explain.explain_predictions

seed: 42
output_path: outputs/resnet34

hydra:
  run:
    dir: ${output_path}

model:
  name: resnet34
  custom_weights_path: null
  num_classes: 1000

visualization:
  num_explanations: 10
  k: 4
  num_prototypes: 4
  img_fn: none

dataset:
  datapath_train: data/imagenet-1k/val
  datapath_val: data/imagenet-1k/val

dataloader:
  batch_size: 512
  num_workers: 4
  pin_memory: true
  shuffle: false

matrix:
  type: orthogonal

prototypes:
  purity_fn: argmax